### ISSUE TITLE
Impossivel de fazer login

### ISSUE THREAD

**Issue by Peabuttt** [netsoft-ruidias/ha-custom-component-coverflex#6]
Boas,

Parece que agora o coverflex envia um pin por sms cada vez que se faz login. O login que existia no HA ficou invalido e não é possível configurar novos logins porque falha sempre.

Cumprimentos

**Comment by jocamane** [comment]
Por aqui também acontece o mesmo.
O que fazer ?

**Comment by jocamane** [comment]
Logger: homeassistant.components.sensor
Source: custom_components/coverflex/api.py:37
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 19:21:22 (1 occurrences)
Last logged: 19:21:22

Error while setting up coverflex platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 289, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/coverflex/sensor.py", line 47, in async_setup_entry
    token = await api.login(config[CONF_USERNAME], config[CONF_PASSWORD])
  File "/config/custom_components/coverflex/api.py", line 37, in login
    raise Exception("Could not retrieve token for user, login failed")
Exception: Could not retrieve token for user, login failed

**Comment by jocamane** [comment]
A tua app Coverflex tem um novo escudo de proteção! 🔐
22 de fevereiro, 2023
 
Olá, Coverflexer!
 
À medida que a Coverflex cresce, temos vindo a implementar medidas adicionais de segurança para garantir que a tua app está devidamente protegida. A maior parte destas medidas têm sido invisíveis, mas agora é tempo de te incluir no processo.
 
O que muda?
Daqui em diante, a tua app tem um sistema de autenticação multi-fator (2 passos) para que possas aceder-lhe. Para além do teu email e password, precisarás também de inserir um código de 6 dígitos que será enviado para o teu número de telemóvel.
 
Autenticação multi-fator 🔐
Autenticação multi-fator é um método de autenticação que requere a um utilizador apresente uma combinação de duas ou mais credenciais para verificar a sua identidade, de forma a conseguir aceder a um determinado recurso, como uma aplicação.
 
Como funciona ao certo neste caso? 
Daqui em diante, de forma a conseguires aceder à tua app Coverflex (mobile ou desktop), irás:
1.	inserir o teu email e password;
2.	receber um SMS com um código de 6 dígitos no teu número de telemóvel;
3.	inserir o código de verificação recebido.
E já está!
 
E se…
… eu não conseguir entrar na app?
•	Assegura-te de que estás a utilizar as credenciais corretas (email e password);
•	Na aplicação móvel, garante que a app está atualizada (última versão);
•	Na web (my.coverflex.com), limpa a cache do browser e carrega novamente a página.
... o meu número de telemóvel estiver errado na app Coverflex?
•	Não te preocupes! Basta entrar em contacto connosco através do chat ou via email para help@coverflex.com e ajudamos-te.
... eu não me lembrar da minha password?
•	Como sempre, caso não te lembres da password, podes recuperá-la clicando em “recuperar password” no ecrã de login. Após escolheres a tua nova password, ser-te-á pedido que insiras o código de 6 dígitos no próximo login na plataforma.
 
❗️Importanter: Se estiveres a usar a aplicação móvel, é crucial atualizá-la para a última versão para que consigas entrar na tua app.
 
É tudo por agora! Daremos mais novidades em breve.
 
Até lá, caso tenhas alguma questão, não hesites em contactar-nos por email para help@coverflex.com ou através do chat na plataforma — estamos sempre disponíveis para ajudar!
 
Até breve
Equipa Coverflex

**Comment by loadedlouie** [comment]
Bem aparentemente não sou o único com  este problema. 
Tenho mixed feillings com este update da CoverFlex. Uma mistura entre "bom trabalho"  e um "Vão-se f.." :)

**Comment by netsoft-ruidias** [comment]
Bom dia

Já tive conhecimento desta limitação e vou tentar perceber se há forma de contornar o login.
Sinceramente não compreendo estas limitações que os bancos impõe, é simplesmente ridículo não dar acesso aos nossos dados. Até compreenderia se a APP permitisse fazer operações (segurança a cima de tudo) mas não é o caso, estas credenciais apenas permitem a consulta do saldo e o histórico. não se compreende, enfim...

Logo que tenha mais notícias eu informo

**Comment by jocamane** [comment]
Boas @netsoft-ruidias 
É para abandonar ou já conseguiste evoluir alguma coisa nesta limitação ?

**Comment by netsoft-ruidias** [comment]
Boa tarde, é possível fazer o login mesmo com o PIN, no entanto sempre que se actualize a entidade é necessário o PIN o que torna a experiencia de utilização muito estranha e sai do "normal" que seria um sensor no home assistant.

Por esse motivo, esta integração não terá novos desenvolvimentos

**Comment by jocamane** [comment]
Ok, Rui. Muito obrigado

**Comment by loadedlouie** [comment]
Boas... Então é para abandonar ?

**Comment by FragMenthor** [comment]
Boas! Ainda não há solução para isto? Obrigado!

**Comment by FragMenthor** [comment]
Bem, para quem esiver interessado, é possível manter um registo bastante aproximado no HA do saldo e movimentos Coverflex, já tenho implementado. Se houver interessados publico algures (talvez CPHA).
O que envolve:
- Notificações da app Coverflex ligadas para todos os movimentos.
- Sensor do telemovel "sensor.mobile_app_<xxxxx>_last_notification" ligado com permissão para ler da aplicação Coverflex.
- Criar "input_number.coverflex_alimentação_saldo"
- Criar "input_number.coverflex_beneficios_saldo"
- Automação para a ler a notificação, interpretar as entradas e saídas de valores e atualizar os "input_number.<yyyyy>_saldo" de acordo com o movimento.
NOTA: pode falhar em caso de utilização de saldo de benefícios em algo que não tenha "*farma*" (farmácias) no nome, mas é melhor que nada e cobre +95% dos casos; podem sempre ser ajustados os valores periodicamente de forma manual.

**Comment by mapb1990** [comment]
> Bem, para quem esiver interessado, é possível manter um registo bastante aproximado no HA do saldo e movimentos Coverflex, já tenho implementado. Se houver interessados publico algures (talvez CPHA). O que envolve:
> 
> * Notificações da app Coverflex ligadas para todos os movimentos.
> * Sensor do telemovel "sensor.mobile_app__last_notification" ligado com permissão para ler da aplicação Coverflex.
> * Criar "input_number.coverflex_alimentação_saldo"
> * Criar "input_number.coverflex_beneficios_saldo"
> * Automação para a ler a notificação, interpretar as entradas e saídas de valores e atualizar os "input_number._saldo" de acordo com o movimento.
>   NOTA: pode falhar em caso de utilização de saldo de benefícios em algo que não tenha "_farma_" (farmácias) no nome, mas é melhor que nada e cobre +95% dos casos; podem sempre ser ajustados os valores periodicamente de forma manual.

@FragMenthor chegaste a fazer alguma coisa?

**Comment by FragMenthor** [comment]
> > Bem, para quem esiver interessado, é possível manter um registo bastante aproximado no HA do saldo e movimentos Coverflex, já tenho implementado. Se houver interessados publico algures (talvez CPHA). O que envolve:
> > 
> > * Notificações da app Coverflex ligadas para todos os movimentos.
> > * Sensor do telemovel "sensor.mobile_app__last_notification" ligado com permissão para ler da aplicação Coverflex.
> > * Criar "input_number.coverflex_alimentação_saldo"
> > * Criar "input_number.coverflex_beneficios_saldo"
> > * Automação para a ler a notificação, interpretar as entradas e saídas de valores e atualizar os "input_number._saldo" de acordo com o movimento.
> >   NOTA: pode falhar em caso de utilização de saldo de benefícios em algo que não tenha "_farma_" (farmácias) no nome, mas é melhor que nada e cobre +95% dos casos; podem sempre ser ajustados os valores periodicamente de forma manual.
> 
> [@FragMenthor](https://github.com/FragMenthor) chegaste a fazer alguma coisa?

Sim, tenho implementado capturando as notificações do telemóvel, já praticamente sem falhas.

**Comment by netsoft-ruidias** [comment]
Boa tarde a todos

**Foi hoje publicada a versão 2, com suporte para OTP (2FA) 💪** 

Devem remover a integração anterior (se ainda existir) e adicionar a nova.
Durante o processo de configuração será pedido o Código OTP que é enviado para o SMS, adicionem o código e a integração deverá funcionar, pelo menos, durante 3 meses sem pedir o código novamente.
Após esses 3 meses, a integração voltará a solicitar o código.

Agradeço que testem esta nova versão e me deem feedback, se funciona bem
https://github.com/netsoft-ruidias/ha-custom-component-coverflex/releases/tag/v2

Disfrutem

**Comment by netsoft-ruidias** [comment]
Só mais um detalhe suculento

A integração agora inclui algumas imagens, experimentem adicionar este cartão:

```yaml
type: picture-entity
entity: sensor.coverflex_name_company_benefits
image:
  media_content_id: /coverflex-brand/card.png
name:
  type: entity
```
